import { createElement } from 'lwc';
import CurrentOrder from 'c/currentOrder';

const APEX_CONTACTS_SUCCESS = [
    {
        Id: '802090000007topAAA',
        Order: {
                Id: '801090000002Qd1AAE', 
                TotalAmount: 37785000},
        OrderId: '801090000002Qd1AAE',
        Product2: {
                Id: '01t09000001c91uAAA',
                Name: 'GenWatt Gasoline 2000kW'},
        Product2Id: '01t09000001c91uAAA',
        ProductName: 'GenWatt Gasoline 2000kW',
        Quantity: 73,
        TotalPrice: 10950000
    },
    {
        Id: '802090000007trWAAQ',
        Order: {
                Id: '801090000002Qd1AAE', 
                TotalAmount: 37785000},
        OrderId: '801090000002Qd1AAE',
        Product2: {
                Id: '01t09000001c91nAAA',
                Name: 'GenWatt Diesel 1000kW'},
        Product2Id: '01t09000001c91nAAA',
        ProductName: 'GenWatt Diesel 1000kW',
        Quantity: 42,
        TotalPrice: 4200000
    }
];

describe('c-current-order', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-current-order', {
            is: CurrentOrder
        });
        document.body.appendChild(element);
        expect(1).toBe(2);
    });
});